/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as ScenarioRouteImport } from "./routes/scenario/route";
import { Route as IndexRouteImport } from "./routes/index/route";

// Create/Update Routes

const ScenarioRouteRoute = ScenarioRouteImport.update({
  path: "/scenario",
  getParentRoute: () => rootRoute,
} as any);

const IndexRouteRoute = IndexRouteImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/scenario": {
      id: "/scenario";
      path: "/scenario";
      fullPath: "/scenario";
      preLoaderRoute: typeof ScenarioRouteImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRouteRoute,
  ScenarioRouteRoute,
});

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/scenario"
      ]
    },
    "/": {
      "filePath": "index/route.tsx"
    },
    "/scenario": {
      "filePath": "scenario/route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
