/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as ScenarioRouteImport } from "./routes/scenario/route";
import { Route as RegisterRouteImport } from "./routes/register/route";
import { Route as LoginRouteImport } from "./routes/login/route";
import { Route as CreateDogovorRouteImport } from "./routes/create-dogovor/route";
import { Route as IndexRouteImport } from "./routes/index/route";

// Create/Update Routes

const ScenarioRouteRoute = ScenarioRouteImport.update({
  path: "/scenario",
  getParentRoute: () => rootRoute,
} as any);

const RegisterRouteRoute = RegisterRouteImport.update({
  path: "/register",
  getParentRoute: () => rootRoute,
} as any);

const LoginRouteRoute = LoginRouteImport.update({
  path: "/login",
  getParentRoute: () => rootRoute,
} as any);

const CreateDogovorRouteRoute = CreateDogovorRouteImport.update({
  path: "/create-dogovor",
  getParentRoute: () => rootRoute,
} as any);

const IndexRouteRoute = IndexRouteImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/create-dogovor": {
      id: "/create-dogovor";
      path: "/create-dogovor";
      fullPath: "/create-dogovor";
      preLoaderRoute: typeof CreateDogovorRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/register": {
      id: "/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof RegisterRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/scenario": {
      id: "/scenario";
      path: "/scenario";
      fullPath: "/scenario";
      preLoaderRoute: typeof ScenarioRouteImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRouteRoute,
  CreateDogovorRouteRoute,
  LoginRouteRoute,
  RegisterRouteRoute,
  ScenarioRouteRoute,
});

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create-dogovor",
        "/login",
        "/register",
        "/scenario"
      ]
    },
    "/": {
      "filePath": "index/route.tsx"
    },
    "/create-dogovor": {
      "filePath": "create-dogovor/route.tsx"
    },
    "/login": {
      "filePath": "login/route.tsx"
    },
    "/register": {
      "filePath": "register/route.tsx"
    },
    "/scenario": {
      "filePath": "scenario/route.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
